language: node_js
node_js:
  - "8"
install:
  - cd client
  - npm install
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    branch: master
    tags: true